FROM node:14.15.1 as building

WORKDIR /app

EXPOSE 3000

COPY ./frontend/package.json ./frontend/package-lock.json ./

RUN npm install

COPY ./frontend/ ./

RUN npm run build

FROM nginx:1.20.2-alpine

WORKDIR /usr/share/nginx/html

COPY --from=building /app/build /usr/share/nginx/html
COPY ./frontend/.nginx/nginx.conf /etc/nginx/conf.d/default.conf

ENV TZ=Asia/Yekaterinburg

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]