FROM python:alpine3.14

WORKDIR /usr/src/app

COPY requirements.txt .

RUN adduser -D user

RUN apk add --no-cache \
     gcc \
     libc-dev \
     libxml2-dev \
     libxslt-dev \
     postgresql-dev \
     bash

RUN pip install --upgrade pip && pip install -r requirements.txt

USER user

ENV PYTHONUNBUFFERED 1
ENV TZ=Asia/Yekaterinburg

EXPOSE 8000

COPY --chmod=755 . .

ENTRYPOINT [ "/usr/src/app/entry.sh" ]